version: "3"
services:
  webapp:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:5000 main:app --reload
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
    ports:
    - "5000:5000"
    - "88:88"
    volumes:
    - ./:/app
